### ISSUE TITLE
SingletonManager - No retry for blob lease renewal failure and eventually causes host crash 

### ISSUE THREAD

**Issue by yuvalpeled1** [Azure/azure-webjobs-sdk#2454]
We experience Azure Functions host crashes due to intermittent blob lease failures.

            public async Task<TaskSeriesCommandResult> ExecuteAsync(CancellationToken cancellationToken)
            {
                // Exceptions wil propagate 
                bool executionSucceeded = await _lockManager.RenewAsync(_lock, cancellationToken);

                TimeSpan delay = _speedupStrategy.GetNextDelay(executionSucceeded: true);
                return new TaskSeriesCommandResult(wait: Task.Delay(delay));
            }

You can see that the GetNextDelay always gets a '**true**' parameter even when the renew method failed. Therefore, the next retry will occur after the lease has expired [because the default retry interval is half of the time of the blob lease period].

#### Expected behavior

A proper retry will be applied if the code will be changed to:
                
`TimeSpan delay = _speedupStrategy.GetNextDelay(executionSucceeded);`

#### Actual behavior

After a single renewAsync failure the host crashes and the following log is emitted:

2020-03-08 11:54:20.7790944     Host.Singleton   2             Log: Singleton lock renewal failed for blob 'sqlfunctions-neu-prd/SqlFunctions.Functions.TiExportAsync.Listener' with error code 409: LeaseIdMismatchWithLeaseOperation. The last successful renewal completed at 2020-03-08T11:51:37.264Z (163514 milliseconds ago) with a duration of 3 milliseconds. The lease period was 60000 milliseconds.
2020-03-08 11:54:20.7837092     Host.Singleton   2             Log: Singleton lock renewal failed for blob 'sqlfunctions-neu-prd/SqlFunctions.Functions.TiIndicatorsStatisticsAsync.Listener' with error code 409: LeaseIdMismatchWithLeaseOperation. The last successful renewal completed at 2020-03-08T11:51:37.267Z (163516 milliseconds ago) with a duration of 6 milliseconds. The lease period was 60000 milliseconds.

Log: An unhandled exception has occurred. Host is shutting down., Exception: 
 
Exception Details
===================================
Exception Type: Microsoft.WindowsAzure.Storage.StorageException
Request Information: Microsoft.WindowsAzure.Storage.RequestResult
Target Site: Void MoveNext()
Message: The lease ID specified did not match the lease ID for the blob.
Help Link: 
Source: Microsoft.WindowsAzure.Storage
HResult: -2146233088
 
Stack Trace Details 
-----------------------------------
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteAsyncInternal[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)
   at Microsoft.Azure.WebJobs.Host.StorageBaseDistributedLockManager.SingletonLockHandle.RenewAsync(ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host.Storage\Singleton\BlobLeaseDistributedLockManager.cs:line 348
   at Microsoft.Azure.WebJobs.Host.SingletonManager.RenewLeaseCommand.ExecuteAsync(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Singleton\SingletonManager.cs:line 334
   at Microsoft.Azure.WebJobs.Host.Timers.TaskSeriesTimer.RunAsync(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Timers\TaskSeriesTimer.cs:line 147

#### Known workarounds
None

#### Related information 
[singletonmanager.cs](https://github.com/Azure/azure-webjobs-sdk/blob/v3.0.17/src/Microsoft.Azure.WebJobs.Host/Singleton/SingletonManager.cs)

[similar issue #822 ](#822 )
[similar issue #2103 ](#2103 )

**Comment by yuvalpeled1** [comment]
I suspect this commit caused the regression (3 years ago)
[commit ](https://github.com/Azure/azure-webjobs-sdk/commit/1d6e30fd719b85b0b0c6cf9e8a0b07e1e0a26bef?diff=split#diff-03975c56f40121be67c2ba5ff90cafd5)

**Comment by drewdelano** [comment]
@mathewc @yuvalpeled1 is this fixed now?

**Comment by mathewc** [comment]
Yes, this fix has been released.

**Comment by ghost** [comment]
Just updated to webjobs sdk 3.0.30 and still seeing this behaviour. One of our webjobs where we use singleton locks, and where the processing of each task is relatively slow, crashes reliably with an error like:

```
fail: Host.Singleton[0]
      Singleton lock renewal failed for blob '132b69019aacca44307452a48f1e036b/Archon.inFlow.Web.WebJobs.ShardBackupWebJobs.CheckForShardsToBackup.fbed5419-5798-40e9-9ad2-c94df6b13a0c' with error code 409: LeaseIdMismatchWithLeaseOperation. The last successful renewal completed at 2021-11-29T17:30:37.996Z (23486 milliseconds ago) with a duration of 3 milliseconds. The lease period was 15000 milliseconds.
fail: Host.Singleton[0]
      Singleton lock renewal failed for blob '132b69019aacca44307452a48f1e036b/Archon.inFlow.Web.WebJobs.ShardBackupWebJobs.CheckForShardsToBackup.39c90a62-0d33-46b2-919b-065c210131bc' with error code 409: LeaseIdMismatchWithLeaseOperation. The last successful renewal completed at 2021-11-29T17:30:40.484Z (20998 milliseconds ago) with a duration of 4 milliseconds. The lease period was 15000 milliseconds.
fail: Host.Singleton[0]
      Singleton lock renewal failed for blob '132b69019aacca44307452a48f1e036b/Archon.inFlow.Web.WebJobs.ShardBackupWebJobs.CheckForShardsToBackup.e656399e-9835-4042-9230-006f9580015b' with error code 409: LeaseIdMismatchWithLeaseOperation. The last successful renewal completed at 2021-11-29T17:30:35.487Z (25994 milliseconds ago) with a duration of 3 milliseconds. The lease period was 15000 milliseconds.
Unhandled exception. Unhandled exception. Unhandled exception. Microsoft.Azure.Storage.StorageException: The lease ID specified did not match the lease ID for the blob.
   at Microsoft.Azure.Storage.Core.Executor.Executor.ExecuteAsync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)
   at Microsoft.Azure.WebJobs.Host.StorageBaseDistributedLockManager.SingletonLockHandle.RenewAsync(ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host.Storage\Singleton\BlobLeaseDistributedLockManager.cs:line 381
   at Microsoft.Azure.WebJobs.Host.SingletonManager.RenewLeaseCommand.ExecuteAsync(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Singleton\SingletonManager.cs:line 341
   at Microsoft.Azure.WebJobs.Host.Timers.TaskSeriesTimer.RunAsync(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Timers\TaskSeriesTimer.cs:line 147
   at Microsoft.Azure.WebJobs.Host.Timers.WebJobsExceptionHandler.<>c__DisplayClass3_0.<OnUnhandledExceptionAsync>b__0() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Timers\WebJobsExceptionHandler.cs:line 55
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart()
Request Information
RequestID:72639e33-a01e-00c9-3046-e5e726000000
RequestDate:Mon, 29 Nov 2021 17:31:01 GMT
StatusMessage:The lease ID specified did not match the lease ID for the blob.
ErrorCode:LeaseIdMismatchWithLeaseOperation
ErrorMessage:The lease ID specified did not match the lease ID for the blob.
RequestId:72639e33-a01e-00c9-3046-e5e726000000
Time:2021-11-29T17:31:01.4777346Z
```
