### ISSUE TITLE
failures in QueueListener should not be fatal. 

### ISSUE THREAD

**Issue by MikeStall** [Azure/azure-webjobs-sdk#944]
Failure to renew the queue message is critical, but failures in the Queue Listener (such as checking queue existence or calling GetMessage) should not be fatal.  Swallow the exception and retry. 

This happens in high load when a network call fails. Currently this brings down the process unnecessarily; instead, we can be a bit more resilient. 

Microsoft.WindowsAzure.Storage.StorageException, Details :Exception: The remote server returned an error: (503) Server Unavailable. at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[T](IAsyncResult result) at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass1`1.<CreateCallback>b__0(IAsyncResult ar) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at Microsoft.Azure.WebJobs.Host.Queues.Listeners.QueueListener.<ExecuteAsync>d__4.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at Microsoft.Azure.WebJobs.Host.Timers.TaskSeriesTimer.<RunAsync>d__d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) at System.Threading.ThreadHelper.ThreadStart() Inner Exception: The remote server returned an error: (503) Server Unavailable. at Microsoft.WindowsAzure.Storage.Shared.Protocol.HttpResponseParsers.ProcessExpectedStatusCodeNoException[T](HttpStatusCode expectedStatusCode, HttpStatusCode actualStatusCode, T retVal, StorageCommandBase`1 cmd, Exception ex) at Microsoft.WindowsAzure.Storage.Queue.CloudQueue.<ExistsImpl>b__1d(RESTCommand`1 cmd, HttpWebResponse resp, Exception ex, OperationContext ctx) at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndGetResponse[T](IAsyncResult getResponseResult) .)

**Comment by mathewc** [comment]
Also came up in ICM incident #36139927. Currently the queue existence check we do is outside of our transient error handling block, so transient errors there will cause the host to go down. We should move that into the error handling block.

**Comment by mathewc** [comment]
Fixed

**Comment by phellsten** [comment]
Using the latest version of WebJobs I'm still getting an unhandled exception after losing network connectivity when running the webjob locally as the QueueTrigger cannot connect to the storage account:
![image](https://user-images.githubusercontent.com/12488644/68265608-aae31e80-00a0-11ea-8ab3-65f0a3a11d72.png)

Is there a way I can catch and ignore this error and keep the webjob running and retrying until the network access is rectified?
